# Generated by Django 6.1 on 2026-10-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="token",
        ),
    ]
