# Generated by Django 6.1 on 2026-08-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(max_length=150, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(max_length=150, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="picture/", verbose_name="Изображение"),
                ),
                (
                    "category",
                    models.CharField(max_length=150, verbose_name="Категория"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Цена за покупку",
                    ),
                ),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                (
                    "updated_at",
                    models.DateField(verbose_name="Дата последнего изменения"),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["category"],
            },
        ),
    ]
