# Generated by Django 6.1 on 2026-09-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(max_length=255, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=255, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Цена за покупку (₽)",
            ),
        ),
    ]
