# Generated by Django 6.1 on 2026-09-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True, upload_to="picture/", verbose_name="Превью"
            ),
        ),
    ]
