# Generated by Django 6.1 on 2026-10-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_product_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликован"),
        ),
    ]
