# Generated by Django 6.1 on 2026-10-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_delete_product", "Can delete product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
